// Self-host Google Fonts: fetch the CSS with a modern UA (→ woff2), keep only the
// latin + latin-ext subsets and the weights we actually use, download the woff2
// files into public/fonts, and emit a local @font-face stylesheet.
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const OUT_DIR = resolve(process.argv[2] || '.', 'public/fonts');
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Syne:wght@600;700;800&family=Instrument+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const slug = (s) => s.toLowerCase().replace(/\s+/g, '-');

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`fonts.googleapis.com ${res.status}`);
  const css = await res.text();

  // Split on subset comments: /* latin */ , /* latin-ext */ , ...
  const parts = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1); // [subset, block, subset, block, ...]
  const faces = [];
  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i];
    const block = parts[i + 1] || '';
    if (!KEEP_SUBSETS.has(subset)) continue;
    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (block.match(/src:\s*url\(([^)]+)\)/) || [])[1];
    const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!family || !weight || !url) continue;
    const file = `${slug(family)}-${weight}-${subset}.woff2`;
    faces.push({ family, weight, subset, url, range: range?.trim(), file });
  }

  let out =
    '/* Self-hosted subset fonts — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n\n';
  for (const f of faces) {
    const bin = await fetch(f.url, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`${f.url} ${bin.status}`);
    await writeFile(resolve(OUT_DIR, f.file), Buffer.from(await bin.arrayBuffer()));
    out +=
      `@font-face {\n` +
      `  font-family: '${f.family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${f.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${f.file}') format('woff2');\n` +
      (f.range ? `  unicode-range: ${f.range};\n` : '') +
      `}\n\n`;
    console.log(`  ${f.file}  (${f.range ? 'ranged' : 'full'})`);
  }
  await writeFile(resolve(OUT_DIR, 'fonts.css'), out);
  console.log(`\n${faces.length} faces → ${OUT_DIR}`);
}
main().catch((e) => {
  console.error('FONT FETCH FAILED:', e.message);
  process.exit(1);
});
